<Manager>:
	Home:
		name: 'home'
		id: home
<Home>:
	BoxLayout:
		orientation: 'vertical'
		Titulo:
			text: 'CONTROLE DE GASTOS'
		Menu:

<Titulo@Label>:
	canvas.before:
		Color:
			rgba: (.94, .88, .78, 1)
		Rectangle:
			size: self.size
			pos: self.pos
	size_hint_y: None
	height: '60dp'
	font_size: '30sp'
	bold: True
	color: (0, 0, 0, 1)

<Menu@BoxLayout>:
	size_hint_y: None
	height: '70dp'
	Button:
	Button:
		text: 'Home'
		on_release: app.root.current = 'home'
	Button: 
